# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

makeCitationEstimate <- function(A, U, d, V) {
    .Call(`_fastadi_makeCitationEstimate`, A, U, d, V)
}

left <- function(x, A) {
    .Call(`_fastadi_left`, x, A)
}

